### ISSUE TITLE
Where is data_download.sh script ?

### ISSUE THREAD

**Issue by spacingout** [lmelvix/visual-question-answering#2]
Thank you for your contribution! But, I can't find "data_download.sh" ....

**Comment by lmelvix** [comment]
Please follow this link : [https://drive.google.com/open?id=0BzPcu5uhlGR3TG85d1lUVFFJRW8](data_download.sh)

**Comment by lmelvix** [comment]
Can you please try this link : [data_download.sh](https://drive.google.com/open?id=0BzPcu5uhlGR3TG85d1lUVFFJRW8) 

I have updated the permissions
